### ISSUE TITLE
The First Bug was found by Windows User 

### ISSUE THREAD

**Issue by JellyXu** [momoko8443/vscode-library-version#1]
## I am prentice to you ,and i was downloaded it in Windows7 vsCode,and when I used it ,I found that it cannot work , i am angry!
the error is that : 
### cannot open package:package.versions. Detail: ENOENT: no such file or directory, open 'C:\c:\Users\hly\Desktop\focusky\node_modules\abbrev\package.json'
yes it is  ~hello,goodbye~!

**Comment by momoko8443** [comment]
@JellyXu this issue has been resolved in v0.1.1
